# -*- coding: utf-8 -*-
"""OTP_Verification_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYsPQHy5kVLi9hJ_qjDJW-c8nq-kIjSZ
"""

import random
import smtplib
from email.message import EmailMessage

"""Generate a 6-digit OTP."""
def generate_otp():
    return random.randint(100000, 999999)


"""Send OTP to the user's email address."""
def send_otp_email(email, otp):
    from_mail = 'mail2lokeshjoshi@gmail.com'
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login('mail2lokeshjoshi@gmail.com', 'bfxs svvd qdvx jnkk')

    msg = EmailMessage()
    msg['Subject'] = 'OTP Verification'
    msg['From'] = from_mail
    msg['To'] = email
    msg.set_content('Your OTP is ' + str(otp))

    server.send_message(msg)
    server.quit()

"""Prompt the user to enter the OTP received in their email."""
def prompt_for_otp():
    return input('Enter the OTP received in your email: ')


"""Verify if the entered OTP matches the generated OTP."""
def verify_otp(entered_otp, generated_otp):
    return entered_otp == generated_otp


def main():
    email = input('Enter your email address: ')
    otp = generate_otp()
    send_otp_email(email, otp)

    max_attempts = 3
    for attempt in range(max_attempts):
        entered_otp = prompt_for_otp()
        if verify_otp(entered_otp, str(otp)):
            print('OTP Verified')
            break
        else:
            print('Invalid OTP. Please try again.')
    else:
        print('You have reached the maximum number of attempts.')

if __name__ == "__main__":
    main()